spring:
  application:
    name: portfolio-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/thi
    username: thi
    password: 123
    hikari:
      schema: portfolio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://0.0.0.0:5432/
    schemas: portfolio
    user: thi
    password: 123
    locations: classpath:db/migration
server:
  port: 8000
