spring:
  application:
    name: portfolio-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://portfolio-db:5432/portfolio
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
server:
  port: 8080
